# Generated by Django 5.2.11 on 2026-03-01 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(help_text='Last 4 digits or account identifier', max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('credit', 'Credit Card'), ('investment', 'Investment Account'), ('other', 'Other')], default='checking', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(help_text="Short identifier (e.g., 'bank-1', 'bank-5')", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('format_type', models.CharField(help_text="Import format (e.g., 'bank-1', 'bank-5')", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='api.account')),
            ],
            options={
                'verbose_name_plural': 'Import Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('institution', 'account_number')},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('original_description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative for expenses, positive for income', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('cleared', 'Cleared')], default='posted', max_length=20)),
                ('transaction_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.category')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='api_transac_date_26e12b_idx'), models.Index(fields=['account', 'date'], name='api_transac_account_777247_idx'), models.Index(fields=['category'], name='api_transac_categor_987e6d_idx'), models.Index(fields=['amount'], name='api_transac_amount_b70359_idx'), models.Index(fields=['transaction_hash'], name='api_transac_transac_50adc1_idx')],
            },
        ),
    ]
