[pytest]
DJANGO_SETTINGS_MODULE = financial_analysis.settings
python_files = test_*.py tests.py tests_*.py

testpaths = tests api
addopts = -v --strict-markers
markers =
    django_db: marks tests that need database (deselect with '-m "not django_db"')
